/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m1.pi;

/**
 *
 * @author julien
 */
public class ContactDialog extends OkCancelDialog {

    /**
     * Creates new form ContactDialog
     */
    public ContactDialog() {
        initComponents();
    }
    
    public static void main(String[] args)
    {
        new ContactDialog().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contactPanel1 = new m1.pi.ContactPanel();

        getjPanel1().setLayout(new java.awt.BorderLayout());
        getjPanel1().add(contactPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private m1.pi.ContactPanel contactPanel1;
    // End of variables declaration//GEN-END:variables
}
